#sanitizing function:

sf<-function(str,sfile="") {
  s1<-gsub(pattern="    ",     replacement="\\\\hspace*{0.2cm}",x=as.character(str))
  s1<-gsub(pattern="  ",       replacement="\\\\hspace*{0.1cm}",x=as.character(s1))
  s1<-gsub(pattern="#",        replacement="\\\\#",x=as.character(s1))
  s1<-gsub(pattern="&",        replacement="\\\\&",x=as.character(s1))
  s1<-gsub(pattern="_",        replacement="\\\\_",x=as.character(s1))
  s1<-gsub(pattern="\u2020",   replacement="$\\\\dagger$",x=as.character(s1))
  s1<-gsub(pattern="\u2021",   replacement="$\\\\ddagger$",x=as.character(s1))
  s1<-gsub(pattern="%",        replacement="\\\\%",x=as.character(s1))
  
  s1<-gsub(pattern="\u00E4",   replacement='\\\\"{a}',x=as.character(s1))  
  s1<-gsub(pattern="\u00C4",   replacement='\\\\"{A}',x=as.character(s1))
  s1<-gsub(pattern="\u00E2",   replacement="\\\\^{a}",x=as.character(s1))
  s1<-gsub(pattern="\u00C2",   replacement="\\\\^{A}",x=as.character(s1))
  s1<-gsub(pattern="\u00E0",   replacement="\\\\`{a}",x=as.character(s1))
  s1<-gsub(pattern="\u00C0",   replacement="\\\\`{A}",x=as.character(s1))
  s1<-gsub(pattern="\u00E1",   replacement="\\\\'{a}",x=as.character(s1))
  s1<-gsub(pattern="\u00C1",   replacement="\\\\'{A}",x=as.character(s1))
  s1<-gsub(pattern="\u00E3",   replacement="\\\\~{a}",x=as.character(s1))
  s1<-gsub(pattern="\u00C3",   replacement="\\\\~{A}",x=as.character(s1))
  
  s1<-gsub(pattern="\u00EB",   replacement='\\\\"{e}',x=as.character(s1)) 
  s1<-gsub(pattern="\u00CB",   replacement='\\\\"{E}',x=as.character(s1))
  s1<-gsub(pattern="\u00EA",   replacement="\\\\^{e}",x=as.character(s1))
  s1<-gsub(pattern="\u00CA",   replacement="\\\\^{E}",x=as.character(s1))
  s1<-gsub(pattern="\u00E8",   replacement="\\\\`{e}",x=as.character(s1))
  s1<-gsub(pattern="\u00C8",   replacement="\\\\`{E}",x=as.character(s1))
  s1<-gsub(pattern="\u00E9",   replacement="\\\\'{e}",x=as.character(s1))
  s1<-gsub(pattern="\u00C9",   replacement="\\\\'{E}",x=as.character(s1))
  s1<-gsub(pattern="\u0115",   replacement="\\\\u{e}",x=as.character(s1))
  s1<-gsub(pattern="\u0114",   replacement="\\\\u{E}",x=as.character(s1))
  s1<-gsub(pattern="\u0113",   replacement="\\\\={e}",x=as.character(s1))
  s1<-gsub(pattern="\u0112",   replacement="\\\\={E}",x=as.character(s1))
  
  s1<-gsub(pattern="\u00EF",   replacement='\\\\"{i}',x=as.character(s1))  
  s1<-gsub(pattern="\u00CF",   replacement='\\\\"{I}',x=as.character(s1))  
  s1<-gsub(pattern="\u00EE",   replacement="\\\\^{i}",x=as.character(s1))
  s1<-gsub(pattern="\u00CE",   replacement="\\\\^{I}",x=as.character(s1))
  s1<-gsub(pattern="\u00EC",   replacement="\\\\`{i}",x=as.character(s1))
  s1<-gsub(pattern="\u00CC",   replacement="\\\\`{I}",x=as.character(s1))
  s1<-gsub(pattern="\u00ED",   replacement="\\\\'{i}",x=as.character(s1))
  s1<-gsub(pattern="\u00CD",   replacement="\\\\'{I}",x=as.character(s1))
  s1<-gsub(pattern="\u0129",   replacement="\\\\~{i}",x=as.character(s1))
  s1<-gsub(pattern="\u0128",   replacement="\\\\~{I}",x=as.character(s1))
  s1<-gsub(pattern="\u012B",   replacement="\\\\={i}",x=as.character(s1))
  s1<-gsub(pattern="\u012A",   replacement="\\\\={I}",x=as.character(s1))
  
  s1<-gsub(pattern="\u00F6",   replacement='\\\\"{o}',x=as.character(s1))
  s1<-gsub(pattern="\u00D6",   replacement='\\\\"{O}',x=as.character(s1))
  s1<-gsub(pattern="\u00F4",   replacement="\\\\^{o}",x=as.character(s1))
  s1<-gsub(pattern="\u00D4",   replacement="\\\\^{O}",x=as.character(s1))
  s1<-gsub(pattern="\u00F2",   replacement="\\\\`{o}",x=as.character(s1))
  s1<-gsub(pattern="\u00D2",   replacement="\\\\`{O}",x=as.character(s1))
  s1<-gsub(pattern="\u00F3",   replacement="\\\\'{o}",x=as.character(s1))
  s1<-gsub(pattern="\u00D3",   replacement="\\\\'{O}",x=as.character(s1))
  s1<-gsub(pattern="\u00F5",   replacement="\\\\~{o}",x=as.character(s1))
  s1<-gsub(pattern="\u00D5",   replacement="\\\\~{O}",x=as.character(s1))
  
  s1<-gsub(pattern="\u00FC",   replacement='\\\\"{u}',x=as.character(s1))
  s1<-gsub(pattern="\u00DC",   replacement='\\\\"{U}',x=as.character(s1))
  s1<-gsub(pattern="\u00FB",   replacement="\\\\^{u}",x=as.character(s1))
  s1<-gsub(pattern="\u00DB",   replacement="\\\\^{U}",x=as.character(s1))
  s1<-gsub(pattern="\u00F9",   replacement="\\\\`{u}",x=as.character(s1))
  s1<-gsub(pattern="\u00D9",   replacement="\\\\`{U}",x=as.character(s1))
  s1<-gsub(pattern="\u00FA",   replacement="\\\\'{u}",x=as.character(s1))
  s1<-gsub(pattern="\u00DA",   replacement="\\\\'{U}",x=as.character(s1))
  s1<-gsub(pattern="\u0169",   replacement="\\\\~{u}",x=as.character(s1))
  s1<-gsub(pattern="\u0168",   replacement="\\\\~{U}",x=as.character(s1))
  s1<-gsub(pattern="\u016B",   replacement="\\\\={u}",x=as.character(s1))
  s1<-gsub(pattern="\u016A",   replacement="\\\\={U}",x=as.character(s1))
  
  s1<-gsub(pattern="\u00E7",   replacement='\\\\c{c}',x=as.character(s1))
  s1<-gsub(pattern="\u00C7",   replacement='\\\\c{C}',x=as.character(s1))
  s1<-gsub(pattern="\u0109",   replacement="\\\\^{c}",x=as.character(s1))
  s1<-gsub(pattern="\u0108",   replacement="\\\\^{c}",x=as.character(s1))
  s1<-gsub(pattern="\u0107",   replacement="\\\\'{c}",x=as.character(s1))
  s1<-gsub(pattern="\u0106",   replacement="\\\\'{c}",x=as.character(s1))
  s1<-gsub(pattern="\u010B",   replacement="\\\\.{c}",x=as.character(s1))
  s1<-gsub(pattern="\u010A",   replacement="\\\\.{c}",x=as.character(s1))
  s1<-gsub(pattern="\u010D",   replacement="\\\\v{c}",x=as.character(s1))
  s1<-gsub(pattern="\u010C",   replacement="\\\\v{s}",x=as.character(s1))

  s1<-gsub(pattern="\u00F1",   replacement="\\\\~{n}",x=as.character(s1))
  s1<-gsub(pattern="\u00D1",   replacement="\\\\~{N}",x=as.character(s1))
  s1<-gsub(pattern="\u0144",   replacement="\\\\'{n}",x=as.character(s1))
  s1<-gsub(pattern="\u0143",   replacement="\\\\'{N}",x=as.character(s1))
  s1<-gsub(pattern="\u0146",   replacement="\\\\c{n}",x=as.character(s1))
  s1<-gsub(pattern="\u0145",   replacement="\\\\c{N}",x=as.character(s1))
  s1<-gsub(pattern="\u0148",   replacement="\\\\v{n}",x=as.character(s1))
  s1<-gsub(pattern="\u0147",   replacement="\\\\v{N}",x=as.character(s1))
   
  s1<-gsub(pattern="\u015B",   replacement="\\\\'{s}",x=as.character(s1))
  s1<-gsub(pattern="\u015A",   replacement="\\\\'{S}",x=as.character(s1))
  s1<-gsub(pattern="\u015D",   replacement="\\\\^{s}",x=as.character(s1))
  s1<-gsub(pattern="\u015E",   replacement="\\\\^{S}",x=as.character(s1))
  s1<-gsub(pattern="\u015F",   replacement="\\\\c{s}",x=as.character(s1))
  s1<-gsub(pattern="\u015E",   replacement="\\\\c{S}",x=as.character(s1))
  s1<-gsub(pattern="\u0161",   replacement="\\\\v{s}",x=as.character(s1))
  s1<-gsub(pattern="\u0160",   replacement="\\\\v{S}",x=as.character(s1))
   
  s1<-gsub(pattern="\u00BAC",  replacement="\\\\textcelsius",x=as.character(s1))
  s1<-gsub(pattern="\u00BA",   replacement="$^\\\\circ$",x=as.character(s1))
  s1<-gsub(pattern=">=",       replacement="$\\\\geq$",x=as.character(s1))
  s1<-gsub(pattern="<=",       replacement="$\\\\leq$",x=as.character(s1))
  s1<-gsub(pattern="\u00B1",   replacement="$\\\\pm$",x=as.character(s1))
  s1<-gsub(pattern="\u03BC",   replacement="{\\\\textmu}",x=as.character(s1))
  s1<-gsub(pattern="\u00A7",   replacement="{\\\\S}",x=as.character(s1))
  s1<-gsub(pattern="\u00B6",   replacement="{\\\\P}",x=as.character(s1))
  
  if (file.exists(sfile)) {
    sftempl<-read.csv(sfile,header=TRUE,encoding="UTF-8",colClasses = "character")
    for (i in 1:nrow(sftempl)) {
      s1<-gsub(pattern=sftempl[i,1], replacement=sftempl[i,2],x=as.character(s1),fixed=TRUE)
    }
  }
  s1
}
